[package]
name = "async_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
scraper = "0.12.0"
tokio = { version = "1.17.0", features = ["full"] }
urlencoding = "2.1.0"
